(()=>{"use strict";
const ROOT="assets/maps",DATA_ROOT="assets/data",ICON_ROOT="assets/icons",SIZE=4096,TILE=256,KEY="deltamap-project-v1",COLORS=["#d5f249","#ff5f55","#42a5ff","#ffffff","#ffb43b","#b47cff"];
const UNIT_TYPES=[['person','小队成员','person'],['deploy_m1a4zztk','M1A4 主战坦克','vehicle'],['deploy_qxtk','GTQ-35 轻型坦克','vehicle'],['deploy_g1bzc','LAV G1 步战车','vehicle'],['deploy_yyzsj','鱼鹰运输直升机','vehicle'],['q_cfz','冲锋舟','vehicle'],['q_lstjp','轮式突击炮','vehicle'],['q_orvtjc','突击车','vehicle'],['q_sxzjc','两栖装甲车','vehicle'],['q_tjzsj','武装直升机','vehicle'],['q_zczsj','侦察直升机','vehicle'],['q_mjz','密集阵','vehicle'],['q_fkc','LAV_AD 防空车','vehicle'],['q_gdjq','固定机枪','fortification'],['q_gdaap','固定防空炮','fortification'],['q_afp','岸防炮','fortification'],['bunker','碉堡','fortification']].map(([id,name,kind])=>({id,name,kind}));
const GADGET_TYPES=[{id:'dataKnife',name:'麦晓雯 · 数据飞刀',icon:'scan-line'},{id:'echoUltimate',name:'回响 · 大招',icon:'radio-tower'}];
const LAYERS=[{id:'boundary',name:'战区边界',icon:'pentagon'},{id:'objective',name:'据点',icon:'flag',match:/^q_jd_/},{id:'base',name:'基地部署点',icon:'shield',match:/jdbsd/},{id:'vehicle',name:'载具',icon:'truck',match:/^q_(cfz|lstjp|orvtjc|sxzjc|tjzsj|zczsj|mjz|fkc)$/},{id:'supply',name:'载具补给站',icon:'fuel',match:/^q_zjbjz$/},{id:'ammo',name:'固定弹药箱',icon:'package',match:/^q_gddyx$/},{id:'weapon',name:'固定武器',icon:'crosshair',match:/^q_(gdjq|gdaap|afp)$/},{id:'device',name:'地图装置',icon:'cable',match:/^q_(hs|dt)$/}];
const MAPS=[['pc','攀升','map_pc','map_pc_zl'],['ljd','临界点','map_ljd_pc','map_ljd_zl'],['gc','贯穿','map_gc','map_gc_zl'],['jq','烬区','map_jq','map_jq_zl'],['qhz','堑壕战','map_qhz','map_qhz_zl'],['df','刀锋','map_df','map_df_zl'],['dg','断轨','map_dg','map_dg'],['hdz','风暴眼','map_hdz','map_hdz'],['jzt','金字塔','map_jzt','map_jzt'],['dc','断层','map_dc','map_dc'],['yz','余震','map_yz','map_yz'],['wmsyh','乌姆斯运河','map_wmsyh','map_wmsyh'],['dsc','克劳狄斗兽场','map_dsc','map_dsc']].map(([id,name,folder,occupyFolder])=>({id,name,folder,occupyFolder}));
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],wrap=$("#canvasWrap"),mapCanvas=$("#mapCanvas"),drawCanvas=$("#drawCanvas"),mc=mapCanvas.getContext("2d"),dc=drawCanvas.getContext("2d");
const MAP_METERS={pc:[2000,2000],ljd:[1263.0958,1263.0958],gc:[1210.631,1226.5868],jq:[1200,1200],qhz:[1200,1200],df:[1140,1140],dg:[1400,1400],hdz:[1744.8202,1744.8202],jzt:[1894.871,1894.871],dc:[1550.1912,1550.1912],yz:[1100,1100],wmsyh:[1894.871,1894.871],dsc:[2000,2000]};
let project=load(),current=MAPS.some(m=>m.id===project.currentMap)?project.currentMap:"pc",mode=project.mode==='occupy'?'occupy':'attack',tool="hand",color=COLORS[0],width=5,unitType='person',gadgetType='dataKnife',view={scale:.2,x:0,y:0,fit:.2},pointer=null,draft=null,textPoint=null,pendingCallout=null,history=[],hIndex=-1,saveTimer=0,toastTimer=0,queued=false,fitted=false,erased=false,collabSilent=false,collabReadOnly=false;const cache=new Map(),poiCache=new Map(),boundaryCache=new Map(),poiIcons=new Map(),coloredUnitIcons=new Map(),poiLoading=new Set();
function uid(prefix='o'){return`${prefix}${Date.now().toString(36)}${Math.random().toString(36).slice(2,8)}`}
function ensureIds(state){MAPS.forEach(map=>{(state.drawings?.[map.id]||[]).forEach(item=>item.id=item.id||uid());(state.callouts?.[map.id]||[]).forEach(item=>item.id=item.id||uid('c'))});return state}
function defaultLayers(){return{boundary:true,objective:true,base:true,vehicle:false,supply:false,ammo:false,weapon:false,device:false}}
function blank(){let drawings={},callouts={};MAPS.forEach(m=>{drawings[m.id]=[];callouts[m.id]=[]});return{version:1,currentMap:"pc",mode:'attack',drawings,callouts,layers:defaultLayers(),stages:{},updatedAt:Date.now()}}
function load(){try{let p=JSON.parse(localStorage.getItem(KEY));if(!p||p.version!==1||!p.drawings)return blank();p.callouts=p.callouts||{};MAPS.forEach(m=>{if(!Array.isArray(p.drawings[m.id]))p.drawings[m.id]=[];if(!Array.isArray(p.callouts[m.id]))p.callouts[m.id]=[]});p.layers={...defaultLayers(),...(p.layers||{})};p.mode=p.mode==='occupy'?'occupy':'attack';p.stages=p.stages||{};delete p.review;return ensureIds(p)}catch{return blank()}}
function objects(){return project.drawings[current]}
function save(now=false,silent=false){clearTimeout(saveTimer);$("#saveState").classList.add("saving");$("#saveState span:last-child").textContent="保存中";const commit=()=>{ensureIds(project);project.updatedAt=Date.now();project.currentMap=current;project.mode=mode;try{localStorage.setItem(KEY,JSON.stringify(project));$("#saveState").classList.remove("saving");$("#saveState span:last-child").textContent="已保存";if(!silent&&!collabSilent)dispatchEvent(new CustomEvent('deltamap:change',{detail:{state:JSON.parse(JSON.stringify(project))}}))}catch{toast("本地空间不足，请导出战术文件")}};now?commit():saveTimer=setTimeout(commit,220)}
function snapshot(){history=history.slice(0,hIndex+1);history.push(JSON.stringify(objects()));if(history.length>60)history.shift();hIndex=history.length-1;historyButtons()}
function resetHistory(){history=[JSON.stringify(objects())];hIndex=0;historyButtons()}
function restore(i){if(i<0||i>=history.length)return;hIndex=i;project.drawings[current]=JSON.parse(history[i]);draft=null;draw();historyButtons();counts();save()}
function historyButtons(){$("#undoButton").disabled=hIndex<=0;$("#redoButton").disabled=hIndex>=history.length-1}
function list(){$("#mapList").innerHTML=MAPS.map((m,i)=>`<button class="map-item${m.id===current?' active':''}" data-map="${m.id}"><span class="map-index">${String(i+1).padStart(2,'0')}</span><span class="map-info"><b>${m.name}</b><small>PC · ${mode==='occupy'?'占领模式':'攻防模式'}</small></span><span class="item-count">${project.drawings[m.id].length||''}</span></button>`).join('')}
function counts(){$("#objectCount").textContent=`${objects().length} 个标注`;$$('.map-item').forEach(e=>e.querySelector('.item-count').textContent=project.drawings[e.dataset.map].length||'')}
function switchMap(id){if(id===current)return closePanel();cancelCallout();current=id;project.currentMap=id;$("#currentMapTitle").textContent=MAPS.find(m=>m.id===id).name;$$('.map-item').forEach(e=>e.classList.toggle('active',e.dataset.map===id));cache.clear();fitted=false;fit();resetHistory();counts();renderCalloutList();loadPois(id);save(true);closePanel();$("#loadingState").classList.remove('hidden')}
function switchMode(next){if(next===mode)return;mode=next;project.mode=mode;$$('#modeSwitch button').forEach(button=>button.classList.toggle('active',button.dataset.mode===mode));list();cache.clear();$("#loadingState").classList.remove('hidden');loadPois(current);queue();save(true)}
function resize(){let r=wrap.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);[mapCanvas,drawCanvas].forEach(c=>{c.width=Math.max(1,Math.round(r.width*d));c.height=Math.max(1,Math.round(r.height*d));c.style.width=r.width+'px';c.style.height=r.height+'px';c.getContext('2d').setTransform(d,0,0,d,0,0)});fitted?queue():fit()}
function fit(){let r=wrap.getBoundingClientRect();if(!r.width||!r.height)return;let margin=r.width<760?12:32;view.fit=Math.min((r.width-margin*2)/SIZE,(r.height-margin*2)/SIZE);view.scale=view.fit;view.x=(r.width-SIZE*view.scale)/2;view.y=(r.height-SIZE*view.scale)/2;fitted=true;queue()}
function clamp(){let r=wrap.getBoundingClientRect(),w=SIZE*view.scale,edge=80;view.x=w<=r.width?(r.width-w)/2:Math.min(edge,Math.max(r.width-w-edge,view.x));view.y=w<=r.height?(r.height-w)/2:Math.min(edge,Math.max(r.height-w-edge,view.y))}
function zoom(f,cx,cy){let r=wrap.getBoundingClientRect(),old=view.scale,next=Math.min(Math.max(2.4,view.fit*12),Math.max(view.fit*.72,old*f)),x=cx??r.width/2,y=cy??r.height/2,wx=(x-view.x)/old,wy=(y-view.y)/old;view.scale=next;view.x=x-wx*next;view.y=y-wy*next;clamp();queue()}
function queue(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;renderMap();draw();$("#zoomLabel").textContent=Math.round(view.scale/view.fit*100)+'%'})}
function tile(m,x,y){let folder=mode==='occupy'?m.occupyFolder:m.folder,key=`${m.id}:${mode}:${x}:${y}`;if(cache.has(key))return cache.get(key);let image=new Image(),entry={image,state:'loading'};entry.promise=new Promise(resolve=>{image.onload=()=>{entry.state='ready';queue();resolve(entry)};image.onerror=()=>{entry.state='error';resolve(entry)}});image.src=`${ROOT}/${folder}/4_${x}_${y}.jpg`;cache.set(key,entry);return entry}
function flatten(value,out=[]){if(Array.isArray(value))value.forEach(item=>flatten(item,out));else if(value&&typeof value==='object')out.push(value);return out}
function poiCategory(icon){return LAYERS.find(layer=>layer.match?.test(icon))?.id}
function gameToWorld(item,info){let x=Number(item.x),y=Number(item.y),xb=info.width/128,yb=info.height/128,px,py;if(info.rotate===90){px=128-(info.centerY+y)/yb;py=-128+(info.centerX-x)/xb}else if(info.rotate===-90){px=128+(info.centerY+y)/yb;py=-128-(info.centerX-x)/xb}else{px=128-(info.centerX-x)/xb;py=-128-(info.centerY+y)/yb}return{x:px*16,y:-py*16}}
function parseBorderPoint(value,info){let match=String(value).match(/X=([-\d.]+),Y=([-\d.]+)/);return match?gameToWorld({x:match[1],y:match[2]},info):null}
function splitBorder(border,info){if(!Array.isArray(border))return[];let polygons=[],points=[];border.forEach(value=>{let point=parseBorderPoint(value,info);if(!point)return;points.push(point);if(points.length>3&&Math.hypot(point.x-points[0].x,point.y-points[0].y)<1){polygons.push(points);points=[]}});if(points.length>2)polygons.push(points);return polygons}
function uniquePolygons(entries,info){let seen=new Set(),polygons=[];entries.forEach(entry=>splitBorder(entry.border||entry,info).forEach(points=>{let first=points[0],key=`${points.length}:${Math.round(first.x)}:${Math.round(first.y)}`;if(seen.has(key))return;seen.add(key);polygons.push({points,name:entry.name||''})}));return polygons}
function extractBoundaries(records,info){let primaryBorder=Array.isArray(info.border2)&&info.border2.length>2?info.border2:info.border,mapEntries=[primaryBorder].filter(border=>Array.isArray(border)&&border.length>2),regionEntries=records.filter(item=>(item.isRegion==='true'||String(item.icon).startsWith('g_qy'))&&Array.isArray(item.border)),objectiveEntries=records.filter(item=>poiCategory(item.icon)==='objective'&&Array.isArray(item.border));return{map:uniquePolygons(mapEntries,info),regions:uniquePolygons(regionEntries,info),objectives:uniquePolygons(objectiveEntries,info)}}
function extractStage(source,info){let records=flatten(source),seen=new Set(),items=records.filter(item=>item.x&&item.y&&item.icon&&item.isRegion!=='true').map(item=>{let category=poiCategory(item.icon);if(!category)return null;let point=gameToWorld(item,info),key=`${item.name}:${Math.round(point.x)}:${Math.round(point.y)}`;if(seen.has(key)||point.x<0||point.y<0||point.x>SIZE||point.y>SIZE)return null;seen.add(key);return{...point,name:item.sub_name||item.name||'地图点位',icon:item.icon,category,region:item.region||''}}).filter(Boolean);return{items,boundaries:extractBoundaries(records,info)}}
function combineStageSets(sets){let itemSeen=new Set(),polygonSeen=new Set(),items=[],boundaries={map:[],regions:[],objectives:[]};sets.forEach(set=>{set.items.forEach(item=>{let key=`${item.icon}:${item.name}:${Math.round(item.x)}:${Math.round(item.y)}`;if(!itemSeen.has(key)){itemSeen.add(key);items.push(item)}});Object.keys(boundaries).forEach(type=>set.boundaries[type].forEach(polygon=>{let first=polygon.points[0]||{},key=`${type}:${polygon.points.length}:${Math.round(first.x||0)}:${Math.round(first.y||0)}`;if(!polygonSeen.has(key)){polygonSeen.add(key);boundaries[type].push(polygon)}}))});return{items,boundaries}}
const poiKey=id=>`${id}:${mode}`;
function stageIndex(){let key=poiKey(current),count=(poiCache.get(key)||[]).length,index=Math.max(0,Math.min(count-1,Number(project.stages[key])||0));project.stages[key]=index;return index}
function currentPois(){let sets=poiCache.get(poiKey(current))||[];return sets[stageIndex()]||[]}
function currentBoundaries(){let sets=boundaryCache.get(poiKey(current))||[];return sets[stageIndex()]||{map:[],regions:[],objectives:[]}}
function renderStage(){let sets=poiCache.get(poiKey(current))||[],count=sets.length,index=stageIndex(),items=sets[index]||[],names=[...new Set(items.filter(item=>item.category==='objective').map(item=>item.name.replace(/^据点/,'')))],label=index===0?'全部据点':names.length?`据点 ${names.join(' / ')}`:count>1?`阶段 ${index}`:'全图';$("#stageLabel").textContent=poiLoading.has(poiKey(current))?'载入中':label;$("#stageSwitch").classList.toggle('disabled',count<=1);$("#prevStage").disabled=count<=1;$("#nextStage").disabled=count<=1}
function changeStage(delta){let sets=poiCache.get(poiKey(current))||[],count=sets.length;if(count<=1)return;let key=poiKey(current);project.stages[key]=(stageIndex()+delta+count)%count;renderStage();renderLayers();draw();save()}
function loadPois(id){let requestedMode=mode,cacheKey=`${id}:${requestedMode}`;if(poiCache.has(cacheKey)){renderLayers();renderStage();draw();return}if(poiLoading.has(cacheKey))return;poiLoading.add(cacheKey);$("#layerSummary").textContent='正在载入点位';renderLayers();renderStage();let script=document.createElement('script');script.src=`${DATA_ROOT}/map_${id}.js`;script.onload=()=>{try{let info=window[id]?.info,dataKey=`${id}_pc${requestedMode==='occupy'?'_s':''}`,source=window[dataKey]?.mapArticle;if(!info||!source)throw new Error('missing');let stages=Array.isArray(source)&&source.some(Array.isArray)?source:[source],stageSets=stages.map(stage=>extractStage(stage,info)),sets=[combineStageSets(stageSets),...stageSets];poiCache.set(cacheKey,sets.map(set=>set.items));boundaryCache.set(cacheKey,sets.map(set=>set.boundaries))}catch{poiCache.set(cacheKey,[[]]);boundaryCache.set(cacheKey,[{map:[],regions:[],objectives:[]}]);toast('该地图点位数据读取失败')}finally{poiLoading.delete(cacheKey);delete window[id];delete window[`${id}_pc`];delete window[`${id}_mobile`];delete window[`${id}_pc_s`];delete window[`${id}_mobile_s`];script.remove();renderLayers();renderStage();draw()}};script.onerror=()=>{poiLoading.delete(cacheKey);poiCache.set(cacheKey,[[]]);boundaryCache.set(cacheKey,[{map:[],regions:[],objectives:[]}]);script.remove();renderLayers();renderStage();toast('无法载入地图点位数据')};document.head.appendChild(script)}
function renderLayers(){let items=currentPois(),boundaries=currentBoundaries(),loading=poiLoading.has(poiKey(current));$("#layerSummary").textContent=loading?'正在载入点位':`${items.length} 个官方点位`;$("#layerList").innerHTML=LAYERS.map(layer=>{let count=layer.id==='boundary'?boundaries.map.length+boundaries.regions.length:items.filter(item=>item.category===layer.id).length,unit=layer.id==='boundary'?' 个区域':' 个点位',enabled=project.layers[layer.id];return`<button class="layer-item${enabled?' enabled':''}" data-layer="${layer.id}"><span class="layer-symbol"><i data-lucide="${layer.icon}"></i></span><span class="layer-copy"><b>${layer.name}</b><small>${loading?'载入中':count+unit}</small></span><span class="layer-toggle"></span></button>`}).join('');window.lucide?.createIcons();let all=LAYERS.every(layer=>project.layers[layer.id]);$("#toggleAllLayers").textContent=all?'全部隐藏':'全部显示'}
function escapeHtml(value){let node=document.createElement('span');node.textContent=String(value||'');return node.innerHTML}
function renderCalloutList(){let callouts=project.callouts[current]||[],allAreasHidden=callouts.length&&callouts.every(item=>item.showArea===false),allNamesHidden=callouts.length&&callouts.every(item=>item.showName===false),allHidden=allAreasHidden&&allNamesHidden;$("#calloutList").innerHTML=callouts.length?callouts.map(item=>`<article class="callout-item" data-callout-id="${item.id}"><div class="callout-item-head"><span class="callout-dot"></span><b>${escapeHtml(item.name)}</b><button class="callout-delete" data-callout-action="delete" title="删除俗名"><i data-lucide="trash-2"></i></button></div><div class="callout-switches"><button class="callout-switch${item.showArea!==false?' enabled':''}" data-callout-action="area">范围</button><button class="callout-switch${item.showName!==false?' enabled':''}" data-callout-action="name">名称</button></div></article>`).join(''):'<div class="callout-empty">当前地图还没有俗名<br>使用画布左侧的俗名工具圈定</div>';$("#toggleAllCalloutAreas").textContent=allAreasHidden?'显示全部范围':'关闭全部范围';$("#toggleAllCalloutNames").textContent=allNamesHidden?'显示全部名称':'关闭全部名称';$("#toggleAllCallouts").textContent=allHidden?'显示所有俗名':'关闭所有俗名';[$("#toggleAllCalloutAreas"),$("#toggleAllCalloutNames"),$("#toggleAllCallouts")].forEach(button=>button.disabled=!callouts.length);window.lucide?.createIcons()}
function getPoiIcon(name){if(poiIcons.has(name))return poiIcons.get(name);let image=new Image(),entry={image,state:'loading'};image.onload=()=>{entry.state='ready';draw()};image.onerror=()=>entry.state='error';image.src=`${ICON_ROOT}/${name}.png`;poiIcons.set(name,entry);return entry}
function getColoredUnitIcon(name,tint){let source=getPoiIcon(name);if(source.state!=='ready')return null;let key=`${name}:${tint}`;if(coloredUnitIcons.has(key))return coloredUnitIcons.get(key);let canvas=document.createElement('canvas'),w=source.image.naturalWidth||48,h=source.image.naturalHeight||48;canvas.width=w;canvas.height=h;let ctx=canvas.getContext('2d');ctx.drawImage(source.image,0,0,w,h);ctx.globalCompositeOperation='source-atop';ctx.fillStyle=tint;ctx.fillRect(0,0,w,h);coloredUnitIcons.set(key,canvas);return canvas}
function renderPolygons(ctx,polygons,{stroke,fill,dash=[],lineWidth=1.5}){ctx.save();ctx.strokeStyle=stroke;ctx.fillStyle=fill;ctx.lineWidth=lineWidth;ctx.lineJoin='round';ctx.setLineDash(dash);polygons.forEach(polygon=>{if(polygon.points.length<3)return;ctx.beginPath();polygon.points.forEach((point,index)=>{let p=w2s(point);index?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y)});ctx.closePath();if(fill)ctx.fill();ctx.stroke()});ctx.restore()}
function drawBoundaries(ctx){let data=currentBoundaries();if(project.layers.boundary){renderPolygons(ctx,data.map,{stroke:'rgba(213,242,73,.72)',fill:'rgba(213,242,73,.018)',dash:[9,6],lineWidth:1.8});renderPolygons(ctx,data.regions,{stroke:'rgba(201,240,74,.48)',fill:'rgba(201,240,74,.028)',dash:[5,5],lineWidth:1.3})}if(project.layers.objective)renderPolygons(ctx,data.objectives,{stroke:'rgba(255,255,255,.72)',fill:'rgba(255,255,255,.05)',lineWidth:1.5})}
function drawPois(ctx){let items=currentPois(),r=wrap.getBoundingClientRect();items.forEach(item=>{if(!project.layers[item.category])return;let p=w2s(item);if(p.x<-24||p.y<-24||p.x>r.width+24||p.y>r.height+24)return;let icon=getPoiIcon(item.icon);if(icon.state==='ready'){ctx.save();ctx.shadowColor='#000a';ctx.shadowBlur=4;ctx.drawImage(icon.image,p.x-14,p.y-14,28,28);ctx.restore()}else{ctx.beginPath();ctx.arc(p.x,p.y,4,0,Math.PI*2);ctx.fillStyle='#d5f249';ctx.fill()}})}
function hoverPoi(event){let tip=$("#poiTooltip");if(tool!=='hand'||pointer){tip.classList.remove('open');return}let s=pos(event),items=currentPois(),found=null;for(let i=items.length-1;i>=0;i--){let item=items[i];if(!project.layers[item.category])continue;let p=w2s(item);if(Math.hypot(s.x-p.x,s.y-p.y)<17){found=item;break}}if(!found){tip.classList.remove('open');return}let layer=LAYERS.find(entry=>entry.id===found.category);tip.querySelector('img').src=`${ICON_ROOT}/${found.icon}.png`;tip.querySelector('b').textContent=found.name;tip.querySelector('small').textContent=layer?.name||'官方点位';tip.style.left=Math.min(wrap.clientWidth-200,s.x+14)+'px';tip.style.top=Math.min(wrap.clientHeight-54,s.y+14)+'px';tip.classList.add('open')}
function range(w,h){return{minX:Math.max(0,Math.floor((-view.x/view.scale)/TILE)),maxX:Math.min(15,Math.floor(((w-view.x)/view.scale)/TILE)),minY:Math.max(0,Math.floor((-view.y/view.scale)/TILE)),maxY:Math.min(15,Math.floor(((h-view.y)/view.scale)/TILE))}}
function renderMap(ctx=mc,w,h){let r=wrap.getBoundingClientRect();w=w||r.width;h=h||r.height;ctx.clearRect(0,0,w,h);ctx.save();ctx.fillStyle='#080a08';ctx.fillRect(0,0,w,h);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';let m=MAPS.find(e=>e.id===current),rg=range(w,h),ready=0,requested=0;for(let y=rg.minY;y<=rg.maxY;y++)for(let x=rg.minX;x<=rg.maxX;x++){requested++;let t=tile(m,x,y),sx=view.x+x*TILE*view.scale,sy=view.y+y*TILE*view.scale,s=Math.ceil(TILE*view.scale)+1;if(t.state==='ready'){ready++;ctx.drawImage(t.image,sx,sy,s,s)}else{ctx.fillStyle=(x+y)%2?'#11140f':'#0f120e';ctx.fillRect(sx,sy,s,s)}}ctx.strokeStyle='#d5f24938';ctx.lineWidth=1;ctx.strokeRect(view.x-.5,view.y-.5,SIZE*view.scale+1,SIZE*view.scale+1);ctx.restore();if(ctx===mc&&requested&&ready>=Math.min(requested,2))$("#loadingState").classList.add('hidden')}
const w2s=p=>({x:view.x+p.x*view.scale,y:view.y+p.y*view.scale}),s2w=p=>({x:(p.x-view.x)/view.scale,y:(p.y-view.y)/view.scale});
function drawGadget(ctx,o){let center=w2s(o.points[0]),metric=MAP_METERS[current]||[2000,2000],radius=(meters,axis)=>meters*SIZE/metric[axis]*view.scale,label=o.gadget==='dataKnife'?'数据飞刀 50+15m':'回响 75m / 120°';ctx.save();ctx.strokeStyle=o.color;ctx.fillStyle=o.color;ctx.lineWidth=2;ctx.setLineDash([8,6]);if(o.gadget==='dataKnife'){[50,65].forEach((meters,index)=>{ctx.beginPath();ctx.ellipse(center.x,center.y,radius(meters,0),radius(meters,1),0,0,Math.PI*2);ctx.globalAlpha=index?.12:.06;ctx.fill();ctx.globalAlpha=.9;ctx.stroke()});ctx.setLineDash([]);ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(center.x-9,center.y+8);ctx.lineTo(center.x+8,center.y-9);ctx.moveTo(center.x+3,center.y-10);ctx.lineTo(center.x+9,center.y-4);ctx.stroke()}else{let angle=Number.isFinite(o.angle)?o.angle:-Math.PI/2,start=angle-Math.PI/3,end=angle+Math.PI/3,rx=radius(75,0),ry=radius(75,1);ctx.beginPath();ctx.moveTo(center.x,center.y);for(let i=0;i<=32;i++){let a=start+(end-start)*i/32;ctx.lineTo(center.x+Math.cos(a)*rx,center.y+Math.sin(a)*ry)}ctx.closePath();ctx.globalAlpha=.13;ctx.fill();ctx.globalAlpha=.9;ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.moveTo(center.x,center.y);ctx.lineTo(center.x+Math.cos(angle)*rx,center.y+Math.sin(angle)*ry);ctx.stroke()}ctx.setLineDash([]);ctx.globalAlpha=1;ctx.font='700 11px Inter,"Microsoft YaHei",sans-serif';ctx.textBaseline='middle';let tw=ctx.measureText(label).width;ctx.fillStyle='#0a0c09df';ctx.fillRect(center.x-tw/2-6,center.y-34,tw+12,22);ctx.fillStyle=o.color;ctx.fillText(label,center.x-tw/2,center.y-23);ctx.restore()}
function drawObject(ctx,o,alpha=1){ctx.save();ctx.globalAlpha=alpha;ctx.strokeStyle=o.color;ctx.fillStyle=o.color;ctx.lineWidth=Math.max(1.5,o.width||5);ctx.lineCap='round';ctx.lineJoin='round';let p=o.points||[];
if(o.type==='gadget'&&p.length){drawGadget(ctx,o)}
else if(o.type==='pen'&&p.length){ctx.beginPath();p.forEach((q,i)=>{q=w2s(q);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y)});ctx.stroke()}
else if((o.type==='line'||o.type==='arrow'||o.type==='measure')&&p.length>1){let a=w2s(p[0]),b=w2s(p[1]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();if(o.type==='arrow'){let angle=Math.atan2(b.y-a.y,b.x-a.x),s=Math.max(12,ctx.lineWidth*3.2);ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-s*Math.cos(angle-Math.PI/6),b.y-s*Math.sin(angle-Math.PI/6));ctx.lineTo(b.x-s*.65*Math.cos(angle),b.y-s*.65*Math.sin(angle));ctx.lineTo(b.x-s*Math.cos(angle+Math.PI/6),b.y-s*Math.sin(angle+Math.PI/6));ctx.closePath();ctx.fill()}if(o.type==='measure'){[a,b].forEach(q=>{ctx.beginPath();ctx.arc(q.x,q.y,4.5,0,Math.PI*2);ctx.fill()});let metric=MAP_METERS[current]||[1000,1000],dx=(p[1].x-p[0].x)*metric[0]/SIZE,dy=(p[1].y-p[0].y)*metric[1]/SIZE,distance=Math.hypot(dx,dy),label=`${distance<100?distance.toFixed(1):Math.round(distance)} m`,mx=(a.x+b.x)/2,my=(a.y+b.y)/2;ctx.font='700 12px Inter,"Microsoft YaHei",sans-serif';ctx.textBaseline='middle';let tw=ctx.measureText(label).width;ctx.fillStyle='#0a0c09df';ctx.fillRect(mx-tw/2-6,my-13,tw+12,26);ctx.strokeStyle=o.color;ctx.lineWidth=1;ctx.strokeRect(mx-tw/2-6,my-13,tw+12,26);ctx.fillStyle=o.color;ctx.fillText(label,mx-tw/2,my)}}
else if(o.type==='rect'&&p.length>1){let a=w2s(p[0]),b=w2s(p[1]);ctx.globalAlpha=alpha*.14;ctx.fillRect(a.x,a.y,b.x-a.x,b.y-a.y);ctx.globalAlpha=alpha;ctx.strokeRect(a.x,a.y,b.x-a.x,b.y-a.y)}
else if(o.type==='circle'&&p.length>1){let a=w2s(p[0]),b=w2s(p[1]),r=Math.hypot(b.x-a.x,b.y-a.y);ctx.beginPath();ctx.arc(a.x,a.y,r,0,Math.PI*2);ctx.globalAlpha=alpha*.14;ctx.fill();ctx.globalAlpha=alpha;ctx.stroke()}
else if(o.type==='marker'&&p.length){let q=w2s(p[0]),s=Math.max(13,(o.width||5)*2.8);ctx.shadowColor='#0008';ctx.shadowBlur=5;ctx.shadowOffsetY=2;ctx.beginPath();ctx.arc(q.x,q.y-s*.36,s*.62,Math.PI*.08,Math.PI*.92,true);ctx.lineTo(q.x,q.y+s);ctx.closePath();ctx.fill();ctx.shadowColor='transparent';ctx.beginPath();ctx.arc(q.x,q.y-s*.36,s*.2,0,Math.PI*2);ctx.fillStyle='#182018';ctx.fill()}
else if(o.type==='unit'&&p.length){let q=w2s(p[0]);if(o.unit==='person'){ctx.shadowColor='#000b';ctx.shadowBlur=5;ctx.beginPath();ctx.arc(q.x,q.y-8,5.5,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(q.x,q.y+5,9,Math.PI,0);ctx.lineTo(q.x+7,q.y+15);ctx.lineTo(q.x-7,q.y+15);ctx.closePath();ctx.fill()}else if(o.unit==='bunker'){ctx.shadowColor='#000b';ctx.shadowBlur=5;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(q.x-18,q.y+13);ctx.lineTo(q.x-15,q.y-7);ctx.lineTo(q.x-9,q.y-14);ctx.lineTo(q.x+9,q.y-14);ctx.lineTo(q.x+15,q.y-7);ctx.lineTo(q.x+18,q.y+13);ctx.closePath();ctx.globalAlpha=alpha*.25;ctx.fill();ctx.globalAlpha=alpha;ctx.stroke();ctx.fillRect(q.x-9,q.y-5,18,6);ctx.fillStyle='#10130f';ctx.fillRect(q.x-6,q.y-3,12,2)}else{let icon=getColoredUnitIcon(o.unit,o.color);ctx.shadowColor='#000b';ctx.shadowBlur=5;ctx.globalAlpha=alpha*.2;ctx.beginPath();ctx.arc(q.x,q.y,20,0,Math.PI*2);ctx.fill();ctx.globalAlpha=alpha;ctx.lineWidth=2.5;ctx.beginPath();ctx.arc(q.x,q.y,20,0,Math.PI*2);ctx.stroke();if(icon){let ratio=Math.min(34/icon.width,34/icon.height),iw=icon.width*ratio,ih=icon.height*ratio;ctx.shadowBlur=4;ctx.drawImage(icon,q.x-iw/2,q.y-ih/2,iw,ih)}}}
else if(o.type==='text'&&p.length){let q=w2s(p[0]),fs=Math.max(14,12+(o.width||5));ctx.font=`600 ${fs}px Inter,"Microsoft YaHei",sans-serif`;ctx.textBaseline='middle';let tw=ctx.measureText(o.text).width,ht=fs+12;ctx.fillStyle='#0a0c09c7';ctx.fillRect(q.x-7,q.y-ht/2,tw+14,ht);ctx.fillStyle=o.color;ctx.fillText(o.text,q.x,q.y)}ctx.restore()}
function calloutCenter(item){if(Array.isArray(item.points)&&item.points.length){return{x:item.points.reduce((sum,p)=>sum+p.x,0)/item.points.length,y:item.points.reduce((sum,p)=>sum+p.y,0)/item.points.length}}return{x:item.x,y:item.y}}
function drawCalloutArea(ctx,item){ctx.beginPath();if(Array.isArray(item.points)&&item.points.length){item.points.forEach((point,index)=>{let p=w2s(point);index?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y)});if(item.points.length>2){ctx.closePath();ctx.fill()}ctx.stroke()}else{let p=w2s(item);ctx.arc(p.x,p.y,item.radius*view.scale,0,Math.PI*2);ctx.fill();ctx.stroke()}}
function drawCallouts(ctx){let callouts=project.callouts[current]||[];if(!callouts.length&&!pendingCallout)return;ctx.save();[...callouts,...(pendingCallout?[{...pendingCallout,showName:false}]:[])].forEach(item=>{let p=w2s(calloutCenter(item));if(item.showArea!==false){ctx.strokeStyle='rgba(80,220,210,.85)';ctx.fillStyle='rgba(45,190,180,.09)';ctx.lineWidth=2;ctx.setLineDash([8,6]);drawCalloutArea(ctx,item)}if(item.showName!==false){ctx.setLineDash([]);ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='700 13px Inter,"Microsoft YaHei",sans-serif';let labelWidth=ctx.measureText(item.name).width;ctx.fillStyle='#071514dc';ctx.fillRect(p.x-labelWidth/2-7,p.y-13,labelWidth+14,26);ctx.strokeStyle='rgba(80,220,210,.75)';ctx.lineWidth=1;ctx.strokeRect(p.x-labelWidth/2-7,p.y-13,labelWidth+14,26);ctx.fillStyle='#74eee5';ctx.fillText(item.name,p.x,p.y)}});ctx.restore()}
function draw(ctx=dc,w,h,clear=true){let r=wrap.getBoundingClientRect();if(clear)ctx.clearRect(0,0,w||r.width,h||r.height);drawBoundaries(ctx);drawPois(ctx);drawCallouts(ctx);objects().forEach(o=>drawObject(ctx,o));if(draft){if(draft.callout){ctx.save();ctx.strokeStyle='#50dcd2';ctx.fillStyle='rgba(45,190,180,.09)';ctx.lineWidth=2;ctx.setLineDash([8,6]);drawCalloutArea(ctx,{points:draft.points});ctx.restore()}else drawObject(ctx,draft,.72)}}
function battleUnits(side,color){let units=[];(side?.infantry||[]).forEach(([x,y])=>units.push({type:'unit',unit:'person',points:[{x,y}],color,width:5}));(side?.vehicles||[]).forEach(([x,y,unit])=>units.push({type:'unit',unit,points:[{x,y}],color,width:5}));return units}
function drawBattleOverlay(ctx){if(current!==window.DELTAMAP_BATTLE?.map||!battlePoint)return;let round=window.DELTAMAP_BATTLE.rounds[battleRound];ctx.save();ctx.strokeStyle='#ffffff';ctx.lineWidth=3;ctx.setLineDash([10,7]);ctx.shadowColor='#000';ctx.shadowBlur=5;ctx.beginPath();battlePoint.front.forEach((point,index)=>{let p=w2s({x:point[0],y:point[1]});index?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y)});ctx.stroke();ctx.restore();battleUnits(battlePoint.attack,round.attackColor).forEach(unit=>drawObject(ctx,unit));battleUnits(battlePoint.defense,round.defenseColor).forEach(unit=>drawObject(ctx,unit));drawBattleLabel(ctx,battlePoint.attack,round.attack,round.attackColor);drawBattleLabel(ctx,battlePoint.defense,round.defense,round.defenseColor)}
function drawBattleLabel(ctx,side,name,color){let all=[...(side.infantry||[]),...(side.vehicles||[])];if(!all.length)return;let x=all.reduce((sum,p)=>sum+p[0],0)/all.length,y=all.reduce((sum,p)=>sum+p[1],0)/all.length,p=w2s({x,y});ctx.save();ctx.font='700 12px "Microsoft YaHei",sans-serif';let label=`${name} ${side.infantry.length}人 / ${side.vehicles.length}载具`,tw=ctx.measureText(label).width;ctx.fillStyle='#0a0c09df';ctx.fillRect(p.x-tw/2-6,p.y-42,tw+12,24);ctx.strokeStyle=color;ctx.strokeRect(p.x-tw/2-6,p.y-42,tw+12,24);ctx.fillStyle=color;ctx.fillText(label,p.x-tw/2,p.y-25);ctx.restore()}
function battleTime(seconds){let value=Math.max(0,Number(seconds)||0);return`${String(Math.floor(value/60)).padStart(2,'0')}:${String(value%60).padStart(2,'0')}`}
function selectBattlePoint(time){let round=window.DELTAMAP_BATTLE?.rounds?.[battleRound];if(!round)return;let best=round.points[0];round.points.forEach(point=>{if(point.time<=time)best=point});battlePoint=best;$("#battleClock").textContent=`回合 ${battleTime(time)} · 视频 ${battleTime(best.videoTime)}`;$("#battleSummary").textContent=`${round.attack} 进攻 / ${round.defense} 防守`;$("#battleAttackStats").style.color=round.attackColor||'#42a5ff';$("#battleDefenseStats").style.color=round.defenseColor||'#ffb43b';$("#battleAttackStats").textContent=`${round.attack} 兵力 ${best.attackForce}`;$("#battleDefenseStats").textContent=`${round.defense} 兵力 ${best.defenseForce}`;$("#battleObjectives").innerHTML=(best.objectives||[]).map(objective=>{let owner=objective.owner==='attack'?(round.attackColor||'#42a5ff'):objective.owner==='defense'?(round.defenseColor||'#ffb43b'):'#8b9387',progress=Math.max(0,Math.min(100,Number(objective.progress)||0));return`<div class="battle-objective" title="${objective.id} 占领进度 ${progress}%"><i class="battle-objective-fill" style="height:${progress}%;--owner:${owner}"></i><span>${objective.id}</span></div>`}).join('')}
function clearBattleReview(silent=false){window.DELTAMAP_BATTLE=null;battlePoint=null;battleRound=0;localStorage.removeItem('deltamap-battle-review-v1');$("#battleRounds").innerHTML='';$("#battleSummary").textContent='未导入复盘';$("#battleClock").textContent='';$("#battleAttackStats").textContent='';$("#battleDefenseStats").textContent='';$("#battleObjectives").innerHTML='';$("#battleScrubber").max=1;$("#battleScrubber").value=0;if(!silent)toast('复盘已清除')}
function renderBattleRounds(){let rounds=window.DELTAMAP_BATTLE?.rounds||[];$("#battleRounds").innerHTML=rounds.map((round,index)=>`<button class="${index===battleRound?'active':''}" data-battle-round="${index}">第 ${round.round} 轮</button>`).join('');let round=rounds[battleRound];if(!round)return clearBattleReview();$("#battleScrubber").max=round.duration;$("#battleScrubber").value=round.points[0].time;selectBattlePoint(round.points[0].time)}
async function importBattleReview(file){try{let data=JSON.parse(await file.text());if(data.schema!=='deltamap-force-review/v1'||!Array.isArray(data.rounds))throw 0;data.rounds=data.rounds.map(round=>({...round,points:Array.isArray(round.points)?round.points.filter(point=>Number.isFinite(point.attackForce)&&Number.isFinite(point.defenseForce)):[]})).filter(round=>round.points.length);if(!data.rounds.length)throw 0;window.DELTAMAP_BATTLE=data;battleRound=0;localStorage.setItem('deltamap-battle-review-v1',JSON.stringify(data));renderBattleRounds();toast('复盘 JSON 已导入')}catch{toast('没有可用的清晰兵力记录')}}
function setBattleVisible(visible){$("#battleTimeline").classList.toggle('review-hidden',!visible);$("#battleToggle").classList.toggle('battle-toggle-active',visible);$("#battleToggle").setAttribute('aria-pressed',String(visible));$("#battleToggle").title=visible?'隐藏复盘':'显示复盘';localStorage.setItem('deltamap-review-visible-v2',visible?'1':'0')}
function bindBattle(){$("#battleRounds").onclick=event=>{let button=event.target.closest('[data-battle-round]');if(!button)return;battleRound=Number(button.dataset.battleRound);renderBattleRounds()};$("#battleScrubber").oninput=event=>selectBattlePoint(Number(event.target.value));$("#importBattleReview").onclick=()=>$("#battleReviewFile").click();$("#clearBattleReview").onclick=()=>clearBattleReview();$("#battleToggle").onclick=()=>setBattleVisible($("#battleTimeline").classList.contains('review-hidden'));$("#battleReviewFile").onchange=event=>{if(event.target.files[0])importBattleReview(event.target.files[0]);event.target.value=''};setBattleVisible(localStorage.getItem('deltamap-review-visible-v2')==='1');window.DELTAMAP_BATTLE?renderBattleRounds():clearBattleReview(true)}
function pos(e){let r=drawCanvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function down(e){if(e.button!==undefined&&e.button!==0)return;if(collabReadOnly&&tool!=='hand'){toast('当前以观察者身份加入，不能编辑');return}closeMenu();hideText();if(pendingCallout)cancelCallout();let s=pos(e),world=s2w(s);pointer={id:e.pointerId,start:s,last:s,world};drawCanvas.setPointerCapture?.(e.pointerId);if(tool==='hand'){let target=!collabReadOnly&&[...objects()].reverse().find(o=>(o.type==='unit'||o.type==='gadget')&&hit(o,s));drawCanvas.classList.add('dragging');if(target){pointer.target=target;pointer.original=target.points.map(p=>({...p}))}else pointer.origin={x:view.x,y:view.y}}else if(tool==='marker'){add({type:'marker',points:[world],color,width});pointer=null}else if(tool==='unit'){add({type:'unit',unit:unitType,points:[world],color,width});pointer=null}else if(tool==='gadget'&&gadgetType==='dataKnife'){add({type:'gadget',gadget:gadgetType,points:[world],color,width});pointer=null}else if(tool==='gadget'){draft={type:'gadget',gadget:gadgetType,points:[world],angle:-Math.PI/2,color,width};draw()}else if(tool==='text'){showText(s,world);pointer=null}else if(tool==='eraser'){erase(s)}else{draft={type:tool==='callout'?'pen':tool,callout:tool==='callout',points:[world,world],color:tool==='callout'?'#50dcd2':color,width};if(tool==='pen'||tool==='callout')draft.points=[world];draw()}}
function move(e){if(!pointer||e.pointerId!==pointer.id)return;let s=pos(e);if(tool==='hand'){if(pointer.target){let dx=(s.x-pointer.start.x)/view.scale,dy=(s.y-pointer.start.y)/view.scale;pointer.target.points=pointer.original.map(p=>({x:p.x+dx,y:p.y+dy}));draw()}else{view.x=pointer.origin.x+s.x-pointer.start.x;view.y=pointer.origin.y+s.y-pointer.start.y;clamp();queue()}}else if(tool==='eraser')erase(s);else if(draft){let world=s2w(s);if(tool==='gadget')draft.angle=Math.atan2(world.y-draft.points[0].y,world.x-draft.points[0].x);else if(tool==='pen'||tool==='callout'){let last=draft.points[draft.points.length-1];if(Math.hypot(world.x-last.x,world.y-last.y)*view.scale>1.8)draft.points.push(world)}else draft.points[1]=world;draw()}pointer.last=s}
function up(e){if(!pointer||e.pointerId!==pointer.id)return;drawCanvas.classList.remove('dragging');if(pointer.target&&Math.hypot(pointer.last.x-pointer.start.x,pointer.last.y-pointer.start.y)>1){snapshot();save()}if(draft){let valid=draft.type==='gadget'||(draft.callout?draft.points.length>2:draft.type==='pen'?draft.points.length>1:Math.hypot(draft.points[1].x-draft.points[0].x,draft.points[1].y-draft.points[0].y)*view.scale>3);if(valid&&draft.callout){pendingCallout={points:draft.points.map(point=>({...point}))};showCalloutEditor(pointer.last)}else if(valid){draft.id=draft.id||uid();objects().push(draft);snapshot();save();counts()}else if(draft.callout)toast('请拖动圈出一个完整范围');draft=null;draw()}if(tool==='eraser'&&erased){snapshot();save();erased=false}pointer=null}
function add(o){o.id=o.id||uid();objects().push(o);snapshot();save();counts();draw()}
function seg(p,a,b){let dx=b.x-a.x,dy=b.y-a.y;if(!dx&&!dy)return Math.hypot(p.x-a.x,p.y-a.y);let t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy)));return Math.hypot(p.x-a.x-t*dx,p.y-a.y-t*dy)}
function hit(o,s){let p=(o.points||[]).map(w2s);if(!p.length)return false;if(o.type==='marker'||o.type==='text'||o.type==='unit'||o.type==='gadget')return Math.hypot(s.x-p[0].x,s.y-p[0].y)<24;if(o.type==='circle'&&p[1])return Math.abs(Math.hypot(s.x-p[0].x,s.y-p[0].y)-Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y))<15;if(o.type==='rect'&&p[1]){let minx=Math.min(p[0].x,p[1].x)-12,maxx=Math.max(p[0].x,p[1].x)+12,miny=Math.min(p[0].y,p[1].y)-12,maxy=Math.max(p[0].y,p[1].y)+12,nx=Math.abs(s.x-p[0].x)<14||Math.abs(s.x-p[1].x)<14,ny=Math.abs(s.y-p[0].y)<14||Math.abs(s.y-p[1].y)<14;return s.x>=minx&&s.x<=maxx&&ny||s.y>=miny&&s.y<=maxy&&nx}return p.slice(0,-1).some((q,i)=>seg(s,q,p[i+1])<15)}
function erase(s){for(let i=objects().length-1;i>=0;i--)if(hit(objects()[i],s)){objects().splice(i,1);erased=true;draw();counts();return}}
function select(t){tool=t;drawCanvas.dataset.tool=t;$$('.tool-btn').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));$("#unitPalette").classList.toggle('open',t==='unit');$("#gadgetPalette").classList.toggle('open',t==='gadget');hideText();if(t!=='callout')cancelCallout()}
function renderUnitPalette(){let person='<span class="person-preview"><i data-lucide="user-round"></i></span>',bunker='<span class="person-preview"><i data-lucide="castle"></i></span>';$("#unitPalette").style.setProperty('--unit-color',color);$("#unitPalette").innerHTML=UNIT_TYPES.map(item=>`<button class="unit-option${item.id===unitType?' active':''}" data-unit="${item.id}" title="${item.name}">${item.kind==='person'?person:item.id==='bunker'?bunker:`<img src="${ICON_ROOT}/${item.id}.png" alt="">`}<span>${item.name}</span></button>`).join('');window.lucide?.createIcons()}
function bindUnitPalette(){renderUnitPalette();$("#unitPalette").onclick=e=>{let button=e.target.closest('.unit-option');if(!button)return;e.stopPropagation();unitType=button.dataset.unit;$$('.unit-option').forEach(item=>item.classList.toggle('active',item===button));select('unit')};$("#colorRow").addEventListener('click',()=>{$("#unitPalette").style.setProperty('--unit-color',color)})}
function renderGadgetPalette(){$("#gadgetPalette").style.setProperty('--unit-color',color);$("#gadgetPalette").innerHTML=GADGET_TYPES.map(item=>`<button class="unit-option${item.id===gadgetType?' active':''}" data-gadget="${item.id}" title="${item.name}"><span class="gadget-option-icon"><i data-lucide="${item.icon}"></i></span><span>${item.name}</span></button>`).join('');window.lucide?.createIcons()}
function bindGadgetPalette(){renderGadgetPalette();$("#gadgetPalette").onclick=event=>{let button=event.target.closest('[data-gadget]');if(!button)return;event.stopPropagation();gadgetType=button.dataset.gadget;renderGadgetPalette();select('gadget')};$("#colorRow").addEventListener('click',()=>{$("#gadgetPalette").style.setProperty('--unit-color',color)})}
function showText(s,w){textPoint=w;let ed=$("#textEditor"),left=Math.max(8,Math.min(wrap.clientWidth-Math.min(260,wrap.clientWidth-32)-8,s.x+10));ed.style.left=left+'px';ed.style.top=Math.max(8,Math.min(wrap.clientHeight-50,s.y-20))+'px';ed.classList.add('open');$("#textInput").value='';setTimeout(()=>$("#textInput").focus())}
function hideText(){$("#textEditor").classList.remove('open');textPoint=null}function commitText(){let value=$("#textInput").value.trim();if(value&&textPoint)add({type:'text',points:[textPoint],text:value,color,width});hideText()}
function showCalloutEditor(screen){let editor=$("#calloutEditor"),left=Math.max(8,Math.min(wrap.clientWidth-Math.min(340,wrap.clientWidth-20)-8,screen.x+10));editor.style.left=left+'px';editor.style.top=Math.max(8,Math.min(wrap.clientHeight-50,screen.y-20))+'px';editor.classList.add('open');$("#calloutInput").value='';setTimeout(()=>$("#calloutInput").focus())}
function cancelCallout(){pendingCallout=null;$("#calloutEditor").classList.remove('open')}
function commitCallout(){let name=$("#calloutInput").value.trim();if(!name||!pendingCallout)return;project.callouts[current].push({id:`c${Date.now().toString(36)}`,name,...pendingCallout,showArea:true,showName:true});cancelCallout();renderCalloutList();save();draw();toast('俗名已保存')}
function toast(msg){let e=$("#toast");e.textContent=msg;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),2200)}function closeMenu(){$("#exportMenu").classList.remove('open')}function closePanel(){$("#mapPanel").classList.remove('open');$("#scrim").classList.remove('open')}
async function png(){let r=wrap.getBoundingClientRect(),m=MAPS.find(e=>e.id===current),rg=range(r.width,r.height),wait=[];for(let y=rg.minY;y<=rg.maxY;y++)for(let x=rg.minX;x<=rg.maxX;x++)wait.push(tile(m,x,y).promise);toast('正在生成图片…');await Promise.all(wait);let ratio=Math.min(2,devicePixelRatio||1),out=document.createElement('canvas');out.width=Math.round(r.width*ratio);out.height=Math.round(r.height*ratio);let ctx=out.getContext('2d');ctx.scale(ratio,ratio);renderMap(ctx,r.width,r.height);draw(ctx,r.width,r.height,false);ctx.fillStyle='#0a0c09c7';ctx.fillRect(14,14,150,43);ctx.fillStyle='#d5f249';ctx.font='700 11px sans-serif';ctx.fillText('DELTAMAP',25,31);ctx.fillStyle='#f1f4ed';ctx.font='600 13px "Microsoft YaHei",sans-serif';ctx.fillText(m.name,25,49);out.toBlob(blob=>{if(!blob)return toast('导出失败');download(blob,`DeltaMap-${m.name}-${stamp()}.png`);toast('PNG 已导出')},'image/png')}
function json(){save(true);download(new Blob([JSON.stringify({...project,exportedAt:Date.now()},null,2)],{type:'application/json'}),`DeltaMap-战术方案-${stamp()}.json`);toast('战术文件已导出')}function download(blob,name){let u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1e3)}function stamp(){let n=new Date(),p=v=>String(v).padStart(2,'0');return`${n.getFullYear()}${p(n.getMonth()+1)}${p(n.getDate())}-${p(n.getHours())}${p(n.getMinutes())}`}
async function importFile(file){try{let p=JSON.parse(await file.text());if(p.version!==1||!p.drawings)throw 0;let next=blank();MAPS.forEach(m=>{next.drawings[m.id]=Array.isArray(p.drawings[m.id])?p.drawings[m.id]:[];next.callouts[m.id]=Array.isArray(p.callouts?.[m.id])?p.callouts[m.id]:[]});next.layers={...defaultLayers(),...(p.layers||{})};next.stages=p.stages||{};next.mode=p.mode==='occupy'?'occupy':'attack';next.currentMap=MAPS.some(m=>m.id===p.currentMap)?p.currentMap:current;project=next;current=next.currentMap;mode=next.mode;list();$$('#modeSwitch button').forEach(button=>button.classList.toggle('active',button.dataset.mode===mode));$("#currentMapTitle").textContent=MAPS.find(m=>m.id===current).name;resetHistory();counts();renderLayers();renderCalloutList();renderStage();loadPois(current);save(true);fitted=false;fit();toast('战术文件已恢复')}catch{toast('无法读取该战术文件')}}
function reviewTime(seconds){let value=Math.max(0,Number(seconds)||0);return`${String(Math.floor(value/60)).padStart(2,'0')}:${String(value%60).padStart(2,'0')}`}
function parseReviewTime(value){let parts=String(value||'').trim().split(':').map(Number);return parts.length===2&&parts.every(Number.isFinite)?Math.max(0,parts[0]*60+Math.min(59,parts[1])):0}
function reviewEscape(value){let node=document.createElement('span');node.textContent=String(value||'');return node.innerHTML}
function reviewValue(value){return Number.isFinite(value)?value:'--'}
function reviewDelta(value,previous){if(!Number.isFinite(value)||!Number.isFinite(previous))return'';let delta=value-previous;if(!delta)return'<span class="review-delta">0</span>';return`<span class="review-delta ${delta>0?'up':'down'}">${delta>0?'+':''}${delta}</span>`}
function reviewForce(units,color){let selected=(units||[]).filter(unit=>unit.color?.toLowerCase()===color?.toLowerCase());return{infantry:selected.filter(unit=>unit.unit==='person').length,vehicles:selected.filter(unit=>unit.unit!=='person').length}}
function pointForTime(time){return[...(project.review.points||[])].sort((a,b)=>a.time-b.time).filter(point=>point.time<=time).pop()||null}
function renderReview(){let review=project.review||defaultReview(),points=[...(review.points||[])].sort((a,b)=>a.time-b.time),duration=Math.max(1,(review.videoEndSecond||0)-(review.videoStartSecond||0),points.at(-1)?.time||0);$("#reviewRound").value=review.round||1;$("#reviewAttack").value=review.attack||'';$("#reviewDefense").value=review.defense||'';$("#reviewAttackColor").value=review.attackColor||'#42a5ff';$("#reviewDefenseColor").value=review.defenseColor||'#ffb43b';$("#reviewVideoStart").value=review.videoStartSecond?reviewTime(review.videoStartSecond):'';$("#reviewVideoEnd").value=review.videoEndSecond?reviewTime(review.videoEndSecond):'';$("#reviewScrubber").max=duration;$("#reviewCount").textContent=`${points.length} 个快照`;$("#reviewTimeline").innerHTML=points.length?points.map((point,index)=>{let previous=points[index-1],attack=reviewEscape(review.attack||'攻方'),defense=reviewEscape(review.defense||'守方'),videoTime=Number.isFinite(point.videoTime)?point.videoTime:(review.videoStartSecond||0)+point.time;return`<article class="review-point${reviewPlayback?.id===point.id?' active':''}" data-review-id="${point.id}"><button class="review-delete" data-delete-review="${point.id}" title="删除快照"><i data-lucide="x"></i></button><div class="review-point-head"><span class="review-point-time">回合 ${reviewTime(point.time)}</span><span class="review-point-stage">比赛 ${reviewTime(videoTime)}</span>${point.stage?`<span class="review-point-stage">${reviewEscape(point.stage)}</span>`:''}</div><div class="review-forces"><div class="review-force attack"><b>${attack}</b><span>步兵 ${reviewValue(point.attackInfantry)}${reviewDelta(point.attackInfantry,previous?.attackInfantry)} · 载具 ${reviewValue(point.attackVehicles)}${reviewDelta(point.attackVehicles,previous?.attackVehicles)}</span></div><div class="review-force defense"><b>${defense}</b><span>步兵 ${reviewValue(point.defenseInfantry)}${reviewDelta(point.defenseInfantry,previous?.defenseInfantry)} · 载具 ${reviewValue(point.defenseVehicles)}${reviewDelta(point.defenseVehicles,previous?.defenseVehicles)}</span></div></div>${point.note?`<p class="review-note">${reviewEscape(point.note)}</p>`:''}</article>`}).join(''):'<div class="review-empty">在地图上摆放双方单位，然后保存当前兵力分布</div>';window.lucide?.createIcons()}
function reviewNumber(id,max=999){return Math.max(0,Math.min(max,Number($(id).value)||0))}
function addReviewPoint(){reviewPlayback=null;let minute=reviewNumber('#reviewMinute',99),second=reviewNumber('#reviewSecond',59),time=minute*60+second,units=objects().filter(object=>object.type==='unit').map(object=>JSON.parse(JSON.stringify(object))),attack=reviewForce(units,project.review.attackColor),defense=reviewForce(units,project.review.defenseColor),point={id:Date.now().toString(36),time,videoTime:(project.review.videoStartSecond||0)+time,stage:$("#reviewStage").value.trim(),attackInfantry:attack.infantry,attackVehicles:attack.vehicles,defenseInfantry:defense.infantry,defenseVehicles:defense.vehicles,units,note:$("#reviewNote").value.trim()};project.review.points=project.review.points.filter(item=>item.time!==time);project.review.points.push(point);project.review.points.sort((a,b)=>a.time-b.time);$("#reviewNote").value='';renderReview();save();draw();toast(`已保存 ${units.length} 个单位的分布快照`)}
function loadReviewPoint(point){$("#reviewMinute").value=Math.floor(point.time/60);$("#reviewSecond").value=point.time%60;$("#reviewStage").value=point.stage||'';$("#reviewNote").value=point.note||'';$("#reviewTimeLabel").textContent=reviewTime(point.time);$("#reviewScrubber").value=point.time;playReviewAt(point.time)}
function playReviewAt(time){let point=pointForTime(time);reviewPlayback=point;$("#reviewPlayTime").textContent=`回合 ${reviewTime(time)} · 比赛 ${reviewTime((project.review.videoStartSecond||0)+time)}`;$("#reviewActivePoint").textContent=point?`${reviewTime(point.time)} ${point.stage||''} · ${point.units?.length||0} 个单位`:'该时间之前没有分布快照';renderReview();draw()}
function bindReview(){let syncMeta=()=>{project.review.round=reviewNumber('#reviewRound',99)||1;project.review.attack=$("#reviewAttack").value.trim();project.review.defense=$("#reviewDefense").value.trim();project.review.attackColor=$("#reviewAttackColor").value;project.review.defenseColor=$("#reviewDefenseColor").value;project.review.videoStartSecond=parseReviewTime($("#reviewVideoStart").value);project.review.videoEndSecond=parseReviewTime($("#reviewVideoEnd").value);renderReview();save()};['#reviewRound','#reviewAttack','#reviewDefense','#reviewAttackColor','#reviewDefenseColor','#reviewVideoStart','#reviewVideoEnd'].forEach(id=>$(id).addEventListener('change',syncMeta));['#reviewMinute','#reviewSecond'].forEach(id=>$(id).addEventListener('input',()=>$("#reviewTimeLabel").textContent=reviewTime(reviewNumber('#reviewMinute',99)*60+reviewNumber('#reviewSecond',59))));$("#reviewScrubber").oninput=event=>playReviewAt(Number(event.target.value));$("#exitReviewPlayback").onclick=()=>{reviewPlayback=null;$("#reviewActivePoint").textContent='已退出播放，可继续编辑地图单位';renderReview();draw()};$("#addReviewPoint").onclick=addReviewPoint;$("#reviewTimeline").onclick=event=>{let remove=event.target.closest('[data-delete-review]');if(remove){if(reviewPlayback?.id===remove.dataset.deleteReview)reviewPlayback=null;project.review.points=project.review.points.filter(point=>point.id!==remove.dataset.deleteReview);renderReview();save();draw();return}let entry=event.target.closest('[data-review-id]'),point=entry&&project.review.points.find(item=>item.id===entry.dataset.reviewId);if(point)loadReviewPoint(point)}}
function bindLayers(){$$('.side-tabs button').forEach(button=>button.onclick=()=>{$$('.side-tabs button').forEach(entry=>{let active=entry===button;entry.classList.toggle('active',active);entry.setAttribute('aria-selected',String(active))});$$('.panel-pane').forEach(pane=>pane.classList.toggle('active',pane.dataset.panelPane===button.dataset.panelTab))});$$('#modeSwitch button').forEach(button=>button.onclick=()=>switchMode(button.dataset.mode));$("#prevStage").onclick=()=>changeStage(-1);$("#nextStage").onclick=()=>changeStage(1);$("#layerList").onclick=event=>{let item=event.target.closest('.layer-item');if(!item)return;project.layers[item.dataset.layer]=!project.layers[item.dataset.layer];renderLayers();draw();save()};$("#toggleAllLayers").onclick=()=>{let enable=!LAYERS.every(layer=>project.layers[layer.id]);LAYERS.forEach(layer=>project.layers[layer.id]=enable);renderLayers();draw();save()};$("#calloutList").onclick=event=>{let entry=event.target.closest('[data-callout-id]'),action=event.target.closest('[data-callout-action]')?.dataset.calloutAction;if(!entry||!action)return;let callouts=project.callouts[current],item=callouts.find(value=>value.id===entry.dataset.calloutId);if(!item)return;if(action==='delete')project.callouts[current]=callouts.filter(value=>value!==item);if(action==='area')item.showArea=item.showArea===false;if(action==='name')item.showName=item.showName===false;renderCalloutList();save();draw()};drawCanvas.addEventListener('pointermove',hoverPoi);drawCanvas.addEventListener('pointerleave',()=>$("#poiTooltip").classList.remove('open'))}
function bind(){$("#mapList").onclick=e=>{let i=e.target.closest('.map-item');if(i)switchMap(i.dataset.map)};$("#toolRail").onclick=e=>{let b=e.target.closest('.tool-btn');if(b)select(b.dataset.tool)};$("#colorRow").onclick=e=>{let b=e.target.closest('.color-swatch');if(!b)return;color=b.dataset.color;$$('.color-swatch').forEach(x=>x.classList.toggle('active',x===b))};$("#widthControl").onclick=e=>{let b=e.target.closest('button');if(!b)return;width=+b.dataset.width;$$('#widthControl button').forEach(x=>x.classList.toggle('active',x===b))};drawCanvas.addEventListener('pointerdown',down);drawCanvas.addEventListener('pointermove',move);drawCanvas.addEventListener('pointerup',up);drawCanvas.addEventListener('pointercancel',up);drawCanvas.addEventListener('wheel',e=>{e.preventDefault();let p=pos(e);zoom(e.deltaY<0?1.14:.875,p.x,p.y)},{passive:false});$("#zoomIn").onclick=()=>zoom(1.25);$("#zoomOut").onclick=()=>zoom(.8);$("#fitView").onclick=fit;$("#undoButton").onclick=()=>restore(hIndex-1);$("#redoButton").onclick=()=>restore(hIndex+1);$("#confirmText").onclick=commitText;$("#textInput").onkeydown=e=>{if(e.key==='Enter')commitText();if(e.key==='Escape')hideText()};$("#exportButton").onclick=e=>{e.stopPropagation();$("#exportMenu").classList.toggle('open')};$("#exportMenu").onclick=e=>{let b=e.target.closest('[data-export]');if(!b)return;closeMenu();if(b.dataset.export==='png')png();if(b.dataset.export==='json')json();if(b.dataset.export==='import')$("#fileInput").click()};document.addEventListener('click',closeMenu);$("#fileInput").onchange=e=>{if(e.target.files[0])importFile(e.target.files[0]);e.target.value=''};$("#mapPanelButton").onclick=()=>{$("#mapPanel").classList.add('open');$("#scrim").classList.add('open')};$("#closeMapPanel").onclick=closePanel;$("#scrim").onclick=closePanel;$("#clearButton").onclick=()=>{if(objects().length)$("#clearDialog").classList.add('open');else toast('当前地图没有标注')};$("#cancelClear").onclick=()=>$("#clearDialog").classList.remove('open');$("#confirmClear").onclick=()=>{project.drawings[current]=[];snapshot();save();counts();draw();$("#clearDialog").classList.remove('open');toast('当前地图已清空')};document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();restore(e.shiftKey?hIndex+1:hIndex-1)}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();restore(hIndex+1)}let keys={1:'hand',2:'pen',3:'arrow',4:'marker',5:'text',6:'eraser'};if(keys[e.key])select(keys[e.key])});addEventListener('beforeunload',()=>save(true))}
function toggleAllCallouts(field){let callouts=project.callouts[current],allHidden=callouts.length&&callouts.every(item=>item[field]===false);callouts.forEach(item=>item[field]=allHidden);renderCalloutList();save();draw()}
function bindCalloutEditor(){$("#confirmCallout").onclick=commitCallout;$("#cancelCallout").onclick=cancelCallout;$("#calloutInput").onkeydown=event=>{if(event.key==='Enter')commitCallout();if(event.key==='Escape')cancelCallout()};$("#toggleAllCalloutAreas").onclick=()=>toggleAllCallouts('showArea');$("#toggleAllCalloutNames").onclick=()=>toggleAllCallouts('showName');$("#toggleAllCallouts").onclick=()=>{let callouts=project.callouts[current],allHidden=callouts.length&&callouts.every(item=>item.showArea===false&&item.showName===false);callouts.forEach(item=>{item.showArea=allHidden;item.showName=allHidden});renderCalloutList();save();draw()}}
function collabClone(value){return JSON.parse(JSON.stringify(value))}
function refreshFromCollab(previousMap=current){current=MAPS.some(map=>map.id===project.currentMap)?project.currentMap:current;mode=project.mode==='occupy'?'occupy':'attack';list();$$('#modeSwitch button').forEach(button=>button.classList.toggle('active',button.dataset.mode===mode));$("#currentMapTitle").textContent=MAPS.find(map=>map.id===current).name;cache.clear();if(previousMap!==current){fitted=false;fit()}resetHistory();counts();renderLayers();renderCalloutList();renderStage();loadPois(current);draw()}
function applyCollabOperation(operation){if(!operation||!operation.type)return;let previousMap=current,payload=operation.payload||{},mapId=payload.mapId;if(operation.type==='object.upsert'&&project.drawings[mapId]){let item=collabClone(payload.object),items=project.drawings[mapId],index=items.findIndex(value=>value.id===item.id);index<0?items.push(item):items[index]=item}else if(operation.type==='object.delete'&&project.drawings[mapId])project.drawings[mapId]=project.drawings[mapId].filter(item=>item.id!==payload.id);else if(operation.type==='callout.upsert'&&project.callouts[mapId]){let item=collabClone(payload.callout),items=project.callouts[mapId],index=items.findIndex(value=>value.id===item.id);index<0?items.push(item):items[index]=item}else if(operation.type==='callout.delete'&&project.callouts[mapId])project.callouts[mapId]=project.callouts[mapId].filter(item=>item.id!==payload.id);else if(operation.type==='meta.set'){if(payload.layers)project.layers={...defaultLayers(),...payload.layers};if(payload.stages)project.stages=collabClone(payload.stages);if(payload.mode)project.mode=payload.mode;if(payload.currentMap)project.currentMap=payload.currentMap}collabSilent=true;ensureIds(project);refreshFromCollab(previousMap);save(true,true);collabSilent=false}
function replaceFromCollab(state){if(!state?.drawings)return;let next=blank();MAPS.forEach(map=>{next.drawings[map.id]=Array.isArray(state.drawings?.[map.id])?collabClone(state.drawings[map.id]):[];next.callouts[map.id]=Array.isArray(state.callouts?.[map.id])?collabClone(state.callouts[map.id]):[]});next.layers={...defaultLayers(),...(state.layers||{})};next.stages=collabClone(state.stages||{});next.mode=state.mode==='occupy'?'occupy':'attack';next.currentMap=MAPS.some(map=>map.id===state.currentMap)?state.currentMap:current;let previousMap=current;project=ensureIds(next);collabSilent=true;refreshFromCollab(previousMap);save(true,true);collabSilent=false}
window.DeltaMapAPI={getState:()=>collabClone(ensureIds(project)),applyOperation:applyCollabOperation,replaceState:replaceFromCollab,setReadOnly:value=>{collabReadOnly=!!value;document.body.classList.toggle('collab-readonly',collabReadOnly);if(collabReadOnly)select('hand')},getMap:()=>current,screenToWorld:point=>s2w(point),worldToScreen:point=>w2s(point),toast};
function init(){localStorage.removeItem('deltamap-battle-review-v1');localStorage.removeItem('deltamap-review-visible-v2');$("#colorRow").innerHTML=COLORS.map((c,i)=>`<button class="color-swatch${i?'':' active'}" style="--swatch:${c}" data-color="${c}" aria-label="颜色 ${i+1}"></button>`).join('');list();$$('#modeSwitch button').forEach(button=>button.classList.toggle('active',button.dataset.mode===mode));$("#currentMapTitle").textContent=MAPS.find(m=>m.id===current).name;drawCanvas.dataset.tool=tool;resetHistory();counts();bind();bindLayers();bindUnitPalette();bindGadgetPalette();bindCalloutEditor();window.lucide?.createIcons();renderLayers();renderCalloutList();renderStage();loadPois(current);new ResizeObserver(resize).observe(wrap);resize()}init();
})();
