(()=>{'use strict';
const api=window.DeltaMapAPI;if(!api)return;
const $=selector=>document.querySelector(selector),panel=$('#collabPanel'),button=$('#collabButton'),canvas=$('#drawCanvas');
const COLORS=['#d5f249','#42a5ff','#ff5f55','#ffb43b','#b47cff','#56e0cf','#f58bd6','#ffffff','#8dd45c','#ff8d52'];
let socket=null,connected=false,joining=null,session=null,baseline=api.getState(),pendingOps=[],reconnectTimer=0,reconnectDelay=1000,members=[],cursors=new Map(),lastCursorAt=0;
const clone=value=>JSON.parse(JSON.stringify(value));
const esc=value=>{let node=document.createElement('span');node.textContent=String(value||'');return node.innerHTML};
function openPanel(){panel.classList.add('open');$('#collabBackdrop').classList.add('open')}
function closePanel(){panel.classList.remove('open');$('#collabBackdrop').classList.remove('open')}
function setConnection(state,text){button.classList.toggle('connected',state==='online');button.classList.toggle('connecting',state==='connecting');let status=$('.collab-status');status.classList.toggle('online',state==='online');status.classList.toggle('offline',state==='offline');$('#collabStatusText').textContent=text}
function send(message){if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify(message))}
function serverUrl(){let value=$('#collabServer').value.trim().replace(/^http/i,'ws').replace(/\/$/,'');localStorage.setItem('deltamap-collab-server',value);return value}
function userName(){let value=$('#collabName').value.trim()||`队员${Math.floor(Math.random()*900+100)}`;$('#collabName').value=value;localStorage.setItem('deltamap-collab-name',value);return value}
function connect(action){clearTimeout(reconnectTimer);joining=action;setConnection('connecting','正在连接服务器');if(socket)socket.close();try{socket=new WebSocket(serverUrl())}catch{return connectionFailed('服务器地址无效')}socket.onopen=()=>{connected=true;reconnectDelay=1000;if(joining?.type==='create')send({type:'create',name:userName(),state:api.getState()});else if(joining?.type==='join')send({type:'join',roomId:joining.roomId,name:userName(),role:joining.role});else if(session)send({type:'join',roomId:session.roomId,name:session.name,role:session.role,clientId:session.clientId})};socket.onmessage=event=>handle(JSON.parse(event.data));socket.onerror=()=>{};socket.onclose=()=>{connected=false;setConnection('offline','连接已断开');if(session){reconnectTimer=setTimeout(()=>connect(null),reconnectDelay);reconnectDelay=Math.min(15000,reconnectDelay*1.8)}}}
function connectionFailed(message){setConnection('offline',message);api.toast(message)}
function applyToState(state,operation){let payload=operation.payload||{},mapId=payload.mapId,key=operation.type.startsWith('callout.')?'callouts':'drawings',item=payload.callout||payload.object;if(operation.type.endsWith('.upsert')){state[key][mapId]=state[key][mapId]||[];let index=state[key][mapId].findIndex(value=>value.id===item.id);index<0?state[key][mapId].push(clone(item)):state[key][mapId][index]=clone(item)}else if(operation.type.endsWith('.delete'))state[key][mapId]=(state[key][mapId]||[]).filter(value=>value.id!==payload.id);else if(operation.type==='meta.set'){state.layers=clone(payload.layers);state.stages=clone(payload.stages);state.mode=payload.mode;state.currentMap=payload.currentMap}return state}
function handle(message){if(message.type==='joined'){session={roomId:message.roomId,clientId:message.clientId,name:message.name,role:message.role,color:message.color};panel.classList.add('in-room');$('#collabRoomCode').textContent=message.roomId;$('#collabRoleText').textContent=message.role==='owner'?'房主':message.role==='observer'?'观察者':'编辑者';api.setReadOnly(message.role==='observer');if(message.snapshot){api.replaceState(message.snapshot);baseline=api.getState()}if(session.role!=='observer'&&pendingOps.length){pendingOps.forEach(operation=>{api.applyOperation(operation);applyToState(baseline,operation);send({type:'operation',operation})});pendingOps=[]}setConnection('online','已实时同步');members=message.members||[];renderMembers();localStorage.setItem('deltamap-collab-session',JSON.stringify({roomId:session.roomId,name:session.name,role:session.role,server:serverUrl(),clientId:session.clientId}));joining=null;return}if(message.type==='operation'){api.applyOperation(message.operation);applyToState(baseline,message.operation);return}if(message.type==='presence'){members=message.members||[];renderMembers();return}if(message.type==='cursor'){if(!session||message.clientId===session.clientId)return;cursors.set(message.clientId,{...message,seen:Date.now()});renderCursors();return}if(message.type==='error')connectionFailed(message.message||'协作操作失败')}
function renderMembers(){$('#collabMemberCount').textContent=`${members.length} / 10`;$('#collabMembers').innerHTML=members.map(member=>`<div class="collab-member"><span class="collab-member-dot" style="--member-color:${member.color}"></span><b>${esc(member.name)}${member.clientId===session?.clientId?'（我）':''}</b><small>${member.role==='owner'?'房主':member.role==='observer'?'观察者':'编辑者'}</small></div>`).join('')}
function flatten(state,key){let result=new Map();Object.entries(state[key]||{}).forEach(([mapId,items])=>(items||[]).forEach(item=>result.set(item.id,{mapId,item})));return result}
function diff(previous,next){let operations=[];[['drawings','object'],['callouts','callout']].forEach(([key,type])=>{let before=flatten(previous,key),after=flatten(next,key);after.forEach((entry,id)=>{let old=before.get(id);if(!old||JSON.stringify(old.item)!==JSON.stringify(entry.item))operations.push({type:`${type}.upsert`,payload:{mapId:entry.mapId,[type]:entry.item}})});before.forEach((entry,id)=>{if(!after.has(id))operations.push({type:`${type}.delete`,payload:{mapId:entry.mapId,id}})})});let oldMeta={layers:previous.layers,stages:previous.stages,mode:previous.mode,currentMap:previous.currentMap},newMeta={layers:next.layers,stages:next.stages,mode:next.mode,currentMap:next.currentMap};if(JSON.stringify(oldMeta)!==JSON.stringify(newMeta))operations.push({type:'meta.set',payload:newMeta});return operations}
addEventListener('deltamap:change',event=>{let next=event.detail.state,operations=diff(baseline,next);if(session&&session.role!=='observer')operations.forEach(operation=>connected?send({type:'operation',operation}):pendingOps.push(operation));baseline=clone(next)});
function renderCursors(){let container=$('#remoteCursors'),now=Date.now(),map=api.getMap();cursors.forEach((cursor,id)=>{if(now-cursor.seen>8000){cursors.delete(id);return}let node=container.querySelector(`[data-cursor-id="${id}"]`);if(!node){node=document.createElement('div');node.className='remote-cursor';node.dataset.cursorId=id;container.appendChild(node)}node.style.display=cursor.mapId===map?'block':'none';node.style.setProperty('--cursor-color',cursor.color||COLORS[0]);node.innerHTML=`<span>${esc(cursor.name)}</span>`;let point=api.worldToScreen({x:cursor.x,y:cursor.y});node.style.left=point.x+'px';node.style.top=point.y+'px'});container.querySelectorAll('.remote-cursor').forEach(node=>{if(!cursors.has(node.dataset.cursorId))node.remove()})}
canvas.addEventListener('pointermove',event=>{if(!session||!connected||Date.now()-lastCursorAt<60)return;let rect=canvas.getBoundingClientRect(),point=api.screenToWorld({x:event.clientX-rect.left,y:event.clientY-rect.top});lastCursorAt=Date.now();send({type:'cursor',mapId:api.getMap(),x:point.x,y:point.y})});setInterval(renderCursors,1000);
document.addEventListener('click',event=>{if(session?.role!=='observer')return;let blocked=event.target.closest('#undoButton,#redoButton,#clearButton,#modeSwitch,#stageSwitch,#layerList,#toggleAllLayers,#calloutList,.callout-bulk');if(blocked){event.preventDefault();event.stopImmediatePropagation();api.toast('观察者不能修改房间内容')}},true);
document.addEventListener('keydown',event=>{if(session?.role==='observer'&&(event.ctrlKey||event.metaKey)&&['z','y'].includes(event.key.toLowerCase())){event.preventDefault();event.stopImmediatePropagation();api.toast('观察者不能修改房间内容')}},true);
button.onclick=openPanel;$('#closeCollab').onclick=closePanel;$('#collabBackdrop').onclick=closePanel;$('#collabRole').onclick=event=>{let selected=event.target.closest('[data-role]');if(!selected)return;$('#collabRole').querySelectorAll('button').forEach(item=>item.classList.toggle('active',item===selected))};$('#createRoom').onclick=()=>connect({type:'create'});$('#joinRoom').onclick=()=>{let roomId=$('#collabRoom').value.trim().toUpperCase(),role=$('#collabRole .active').dataset.role;if(!roomId)return api.toast('请输入房间号');connect({type:'join',roomId,role})};$('#copyRoom').onclick=async()=>{let value=session?.roomId||'';try{await navigator.clipboard.writeText(value)}catch{let input=document.createElement('textarea');input.value=value;document.body.appendChild(input);input.select();document.execCommand('copy');input.remove()}api.toast('房间号已复制')};$('#leaveRoom').onclick=()=>{session=null;joining=null;pendingOps=[];clearTimeout(reconnectTimer);socket?.close();socket=null;members=[];cursors.clear();panel.classList.remove('in-room');api.setReadOnly(false);localStorage.removeItem('deltamap-collab-session');setConnection('offline','未连接');renderCursors()};
$('#collabServer').value=localStorage.getItem('deltamap-collab-server')||'ws://localhost:8787';$('#collabName').value=localStorage.getItem('deltamap-collab-name')||'';try{let saved=JSON.parse(localStorage.getItem('deltamap-collab-session'));if(saved?.roomId){$('#collabServer').value=saved.server||$('#collabServer').value;$('#collabName').value=saved.name||$('#collabName').value;session=saved;connect(null)}}catch{}window.lucide?.createIcons();
})();
